### ISSUE TITLE
build errors on latest ubuntu due to change in definitions

### ISSUE THREAD

**Issue by jsridhara** [psankar/simplefs#6]
Hi , I just downloaded this code and did make on ubuntu. I am getting quite some build errors. Looks like headers have changed a lot.
For ex :  simple.c:187:14 , Struct file has no member called  f_dentry .
simple.c:12:0: include/linux/fs.h:2688:16: note: expected ‘struct kiocb *’ but argument is of type ‘struct file *’ extern ssize_t generic_write_checks(struct kiocb *, struct iov_iter *);
----------------------------------------------------------------------------------------
Here is list of build errors
jsridhara@ubuntu:~/code/sankar/simplefs-master$ make
make -C /lib/modules/4.4.0-65-generic/build M=/home/jsridhara/code/sankar/simplefs-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-65-generic'
  CC [M]  /home/jsridhara/code/sankar/simplefs-master/simple.o
/home/jsridhara/code/sankar/simplefs-master/simple.c: In function ‘simplefs_iterate’:
/home/jsridhara/code/sankar/simplefs-master/simple.c:187:14: error: ‘struct file’ has no member named ‘f_dentry’
  inode = filp->f_dentry->d_inode;
              ^
/home/jsridhara/code/sankar/simplefs-master/simple.c:203:14: error: ‘struct file’ has no member named ‘f_dentry’
          filp->f_dentry->d_name.name);
              ^
/home/jsridhara/code/sankar/simplefs-master/simple.c: In function ‘simplefs_write’:
/home/jsridhara/code/sankar/simplefs-master/simple.c:378:32: warning: passing argument 1 of ‘generic_write_checks’ from incompatible pointer type [-Wincompatible-pointer-types]
  retval = generic_write_checks(filp, ppos, &len, 0);
                                ^
In file included from /home/jsridhara/code/sankar/simplefs-master/simple.c:12:0:
include/linux/fs.h:2688:16: note: expected ‘struct kiocb *’ but argument is of type ‘struct file *’
 extern ssize_t generic_write_checks(struct kiocb *, struct iov_iter *);
                ^
/home/jsridhara/code/sankar/simplefs-master/simple.c:378:38: warning: passing argument 2 of ‘generic_write_checks’ from incompatible pointer type [-Wincompatible-pointer-types]
  retval = generic_write_checks(filp, ppos, &len, 0);
                                      ^
In file included from /home/jsridhara/code/sankar/simplefs-master/simple.c:12:0:
include/linux/fs.h:2688:16: note: expected ‘struct iov_iter *’ but argument is of type ‘loff_t * {aka long long int *}’
 extern ssize_t generic_write_checks(struct kiocb *, struct iov_iter *);
                ^
/home/jsridhara/code/sankar/simplefs-master/simple.c:378:11: error: too many arguments to function ‘generic_write_checks’
  retval = generic_write_checks(filp, ppos, &len, 0);
           ^
In file included from /home/jsridhara/code/sankar/simplefs-master/simple.c:12:0:
include/linux/fs.h:2688:16: note: declared here
 extern ssize_t generic_write_checks(struct kiocb *, struct iov_iter *);
                ^
scripts/Makefile.build:258: recipe for target '/home/jsridhara/code/sankar/simplefs-master/simple.o' failed
make[2]: *** [/home/jsridhara/code/sankar/simplefs-master/simple.o] Error 1
Makefile:1420: recipe for target '_module_/home/jsridhara/code/sankar/simplefs-master' failed
make[1]: *** [_module_/home/jsridhara/code/sankar/simplefs-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-65-generic'
Makefile:8: recipe for target 'ko' failed
make: *** [ko] Error 2

**Comment by psankar** [comment]
Patches are welcome :) 

I don't have enough time to keep the sources the sources updated for the latest releases. The kernel code does move fast.

If you are interested in learning the fundamental concepts of fs, you could install an older version of the kernel, headers and play with the code.

**Comment by jsridhara** [comment]
Oh ok nps, I wanted to make sure that I am not missing any build steps.
